name: lint template

on:
  push:
    paths:
      - 'template/**'
  pull_request:
    paths:
      - 'template/**'
    branches:
      - main

jobs:
  lint_template:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - name: install
        run: pnpm i
        working-directory: ./template

      - name: lint
        run: npm run lint
        working-directory: ./template
